// ガチャの便利機能（無料ガチャ・ピックアップ属性・まとめ引き・演出スキップ・履歴）を撮影
const { chromium } = require('/opt/node22/lib/node_modules/playwright');
const fs = require('fs');
const OUT = process.env.OUT || '/tmp/shots';
fs.mkdirSync(OUT, { recursive: true });
(async () => {
  const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium', args: ['--no-proxy-server'] });
  const page = await (await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, hasTouch: true })).newPage();
  const errs = [];
  page.on('console', m => { if ((m.type() === 'error' || m.type() === 'warning') && !/fonts\.g|ERR_FAILED/.test(m.text())) errs.push(m.type() + ': ' + m.text()); });
  page.on('pageerror', e => errs.push('PAGEERROR: ' + e.message));
  const FD = process.env.FONTDIR;
  await page.route(/fonts\.googleapis\.com/, r => FD ? r.fulfill({ contentType: 'text/css', body: fs.readFileSync(FD + '/fonts.css', 'utf8') }) : r.abort());
  await page.route(/fonts\.gstatic\.com/, r => { try { r.fulfill({ contentType: 'font/woff2', body: fs.readFileSync(FD + '/' + r.request().url().replace('https://fonts.gstatic.com/', '').replace(/\//g, '_')) }); } catch (e) { r.abort(); } });
  await page.goto('http://localhost:8765/index.html');
  await page.waitForTimeout(500);
  const snap = n => page.screenshot({ path: `${OUT}/ga-${n}.png` });
  await page.evaluate(() => { const s = Meta.save; s.flags.welcome = true; s.flags.tutorialDone = true; s.login.last = todayStr(); s.tickets = 6; s.premium = 3; s.coins = 5000; Meta.persist(); Game.enterHome(); });
  await page.waitForTimeout(400);
  await snap('01-home');
  await page.evaluate(() => Screens.show('gacha'));
  await page.waitForTimeout(400);
  await snap('02-gacha');
  await page.evaluate(() => { Meta.save.gacha.focus = 'rhythm'; UI.gacha(); Settings.gachaFast = true; $('.g-fast input').checked = true; });
  await page.waitForTimeout(200);
  await page.evaluate(() => { $('#scr-gacha .scroll').scrollTop = 300; });
  await page.waitForTimeout(200);
  await snap('03-focus');
  await page.evaluate(() => UI.buyPack('nt'));
  await page.waitForSelector('.g-summary', { timeout: 10000 });
  await page.waitForTimeout(900);
  await snap('04-summary-fast');
  const tally = await page.evaluate(() => { const ids = Meta.save.gacha.log[0].ids; return { n: ids.length, rhythm: ids.filter(id => CARDS[id].tribe === 'rhythm').length }; });
  console.log('bulk pull', JSON.stringify(tally));
  await page.evaluate(() => { $('.gacha-ov [data-a="close"]').click(); });
  await page.waitForTimeout(300);
  await page.evaluate(() => UI.gachaLog());
  await page.waitForTimeout(400);
  await snap('05-log');
  console.log('ERRORS:', errs.length ? '\n' + errs.join('\n') : 'none');
  await browser.close();
})();
