// 追加の5つの軸（迎撃・呪い・巨大化・群れ・トークン）を実際のバトル画面で確認する
const { chromium } = require('/opt/node22/lib/node_modules/playwright');
const fs = require('fs');
const OUT = process.env.OUT || '/tmp/shots';
fs.mkdirSync(OUT, { recursive: true });
(async () => {
  const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium', args: ['--no-proxy-server'] });
  const page = await (await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, hasTouch: true })).newPage();
  const errs = [];
  page.on('console', m => { if ((m.type() === 'error' || m.type() === 'warning') && !/fonts\.g/.test(m.text())) errs.push(m.type() + ': ' + m.text()); });
  page.on('pageerror', e => errs.push('PAGEERROR: ' + e.message));
  const FD = process.env.FONTDIR;
  await page.route(/fonts\.googleapis\.com/, r => FD ? r.fulfill({ contentType: 'text/css', body: fs.readFileSync(FD + '/fonts.css', 'utf8') }) : r.abort());
  await page.route(/fonts\.gstatic\.com/, r => { try { r.fulfill({ contentType: 'font/woff2', body: fs.readFileSync(FD + '/' + r.request().url().replace('https://fonts.gstatic.com/', '').replace(/\//g, '_')) }); } catch (e) { r.abort(); } });
  await page.goto('http://localhost:8765/index.html');
  await page.waitForTimeout(500);
  const snap = n => page.screenshot({ path: `${OUT}/ax2-${n}.png` });
  await page.evaluate(() => { const s = Meta.save; s.flags.welcome = true; s.flags.tutorialDone = true; s.login.last = todayStr(); Settings.tips = false; Meta.persist(); Game.enterHome(); });
  await page.waitForTimeout(300);
  await page.evaluate(() => { Settings.speed = 1; Time.speed = 1; Game.startStage('3-1'); });
  await page.waitForTimeout(300);
  await page.mouse.click(195, 400);
  await page.waitForFunction(() => B.G && B.G.active === 0 && !B.G.busy, null, { timeout: 30000 });
  await page.evaluate(async () => {
    B.view = null;
    B.G.P[1].board = [null, null, null, null, null];
    await B.summon(1, 'm_drone', 2); await B.summon(1, 'n_ox', 0);
    B.view = View;
    const P = B.G.P[0];
    P.hand = ['ty_leader', 'ty_box', 'sw_hive', 'hx_curse', 'se_watch', 'ti_seed'].map(id => ({ uid: B._uid++, id }));
    P.energy = 30;
    BUI.sync(); BUI.syncHand();
  });
  const play = (id, lane, kind) => page.evaluate(([id, lane, kind]) => { const c = B.G.P[0].hand.find(x => x.id === id); const t = B.targetsFor(0, c).find(x => kind ? x.kind === kind : x.lane === lane); return BUI.play(c, t); }, [id, lane, kind]);
  await play('ty_leader', 0); await page.waitForTimeout(300);
  await play('ty_box', null, 'none'); await page.waitForTimeout(400);
  await play('se_watch', 3);
  await play('hx_curse', null, 'none'); await page.waitForTimeout(400);
  await play('ti_seed', null, 'none'); await page.waitForTimeout(400);
  await snap('01-board');
  await page.evaluate(() => BUI.endTurn());
  await page.waitForTimeout(2600);
  await snap('03-enemy-turn');
  await page.waitForFunction(() => B.G.over || (!B.G.busy && B.G.active === 0), null, { timeout: 60000 });
  await page.evaluate(() => BUI.toggleLog(true));
  await page.waitForTimeout(300);
  await snap('04-log');
  await page.evaluate(() => { BUI.toggleLog(false); UI.howto(); });
  await page.waitForTimeout(400);
  await page.evaluate(() => { const m = $('.modal .howto'); if (m) m.closest('.modal').scrollTop = 99999; });
  await snap('05-howto');
  console.log('ERRORS:', errs.length ? '\n' + errs.join('\n') : 'none');
  await browser.close();
})();
