// アタック前の効果と、カウント中に倒された時の発動を確認する
const { chromium } = require('/opt/node22/lib/node_modules/playwright');
const fs = require('fs');
const OUT = process.env.OUT || '/tmp/shots';
fs.mkdirSync(OUT, { recursive: true });
(async () => {
  const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium', args: ['--no-proxy-server'] });
  const page = await (await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, hasTouch: true })).newPage();
  const errs = [];
  page.on('console', m => { if (m.type() === 'error' || m.type() === 'warning') errs.push(m.type() + ': ' + m.text()); });
  page.on('pageerror', e => errs.push('PAGEERROR: ' + e.message));
  const FD = process.env.FONTDIR;
  await page.route(/fonts\.googleapis\.com/, r => FD ? r.fulfill({ contentType: 'text/css', body: fs.readFileSync(FD + '/fonts.css', 'utf8') }) : r.abort());
  await page.route(/fonts\.gstatic\.com/, r => { try { r.fulfill({ contentType: 'font/woff2', body: fs.readFileSync(FD + '/' + r.request().url().replace('https://fonts.gstatic.com/', '').replace(/\//g, '_')) }); } catch (e) { r.abort(); } });
  await page.goto('http://localhost:8765/index.html');
  await page.waitForTimeout(500);
  const snap = n => page.screenshot({ path: `${OUT}/tr-${n}.png` });
  await page.evaluate(() => { Meta.save.flags.welcome = true; Meta.save.flags.tutorialDone = true; Meta.save.login.last = todayStr(); Meta.persist(); Game.enterHome(); });
  await page.waitForTimeout(300);
  await page.evaluate(() => { Settings.speed = 1; Time.speed = 1; Game.startStage('3-1'); });
  await page.waitForTimeout(300);
  await page.mouse.click(195, 400);
  await page.waitForTimeout(2300);
  await page.evaluate(async () => {
    B.view = null;
    B.G.P[1].board = [null, null, null, null, null];
    await B.summon(1, 'c_bomb', 2); await B.summon(1, 'n_dog', 0);
    B.view = View;
    const P = B.G.P[0];
    P.hand = ['mi_egg', 'm_satellite', 'su_bunny', 'b_imp'].map(id => ({ uid: B._uid++, id }));
    P.energy = 30;
    BUI.sync();
  });
  const play = (id, lane) => page.evaluate(([id, lane]) => { const c = B.G.P[0].hand.find(x => x.id === id); const t = B.targetsFor(0, c).find(x => x.lane === lane); return BUI.play(c, t); }, [id, lane]);
  await play('b_imp', 2); await play('mi_egg', 1); await play('m_satellite', 3); await play('su_bunny', 4);
  await page.waitForTimeout(400);
  await snap('01-predict');
  await page.evaluate(() => BUI.endTurn());
  await page.waitForTimeout(1500);
  await snap('02-preattack');
  await page.waitForTimeout(1800);
  await snap('03-burst');
  await page.waitForFunction(() => B.G.over || (!B.G.busy && B.G.active === 0), null, { timeout: 60000 });
  await page.evaluate(() => BUI.toggleLog(true));
  await page.waitForTimeout(300);
  await snap('04-log');
  console.log('ERRORS:', errs.length ? '\n' + errs.join('\n') : 'none');
  await browser.close();
})();
